version: "3.3"

services:
  web:
    build: ./docker/nginx/
    image: 16nsk/nginx:1.0.0
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/app:delegated
      - web-etc:/etc/nginx/external:consistent
    links:
      - workers
  workers:
    build: ./docker/php/
    image: 16nsk/drupal-php:1.0.0
    ports:
      - "9000"
    environment:
      - ENV=${ENV}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_PUBLIC=${AWS_BUCKET_PUBLIC}
      - AWS_BUCKET_PRIVATE=${AWS_BUCKET_PRIVATE}
    volumes:
      - .:/app:delegated
    links:
      - db
      - cache
      - search
  drupal:
    build: ./docker/drupal/
    image: 16nsk/drupal:1.0.0
    ports:
      - "8888"
    environment:
      - ENV=${ENV}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_PUBLIC=${AWS_BUCKET_PUBLIC}
      - AWS_BUCKET_PRIVATE=${AWS_BUCKET_PRIVATE}
    volumes:
      - .:/app:consistent
      - ./cache/composer:/root/.composer/cache:consistent
    links:
      - db
      - cache
      - search
  db:
    image: mariadb:10.2.7
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
  cache:
    image: redis:4.0.1
    ports:
      - "6379"
    command: redis-server --appendonly yes
    volumes:
      - data-cache:/data
  search:
    image: solr:6.6.0
    ports:
     - "8983"
    volumes:
      - ./docker/solr/conf/6.x:/myconfig/conf
      - data-search:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - "/myconfig"

volumes:
  data-db: {}
  data-cache: {}
  data-search: {}
  web-etc: {}
  composer-cache: {}
