version: "3.3"

services:
  web:
    image: 16nsk/nginx:1.0.0
    ports:
      - "18080:80"
      - "18443:443"
    volumes:
      - ./app:/app:delegated
      - web-etc:/etc/nginx/external
    links:
      - workers
  workers:
    image: 16nsk/php:1.0.0
    environment:
      - ENV=${ENV}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_PUBLIC=${AWS_BUCKET_PUBLIC}
      - AWS_BUCKET_PRIVATE=${AWS_BUCKET_PRIVATE}
    volumes:
      - ./app:/app:delegated
      - ./config/php.development.ini:/usr/local/etc/php/php.ini:delegated
    links:
      - db
      - cache
      - search
      - mail
  drupal:
    image: 16nsk/drupal:1.0.0
    environment:
      - ENV=${ENV}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_PUBLIC=${AWS_BUCKET_PUBLIC}
      - AWS_BUCKET_PRIVATE=${AWS_BUCKET_PRIVATE}
    volumes:
      - ./app:/app:consistent
      - ./cache/composer:/root/.composer/cache:consistent
      - ./config/php.development.ini:/usr/local/etc/php/php.ini:delegated
    links:
      - db
      - cache
      - search
      - mail
  db:
    image: mariadb:10.2.8
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - data-db:/var/lib/mysql
  cache:
    image: redis:4.0.1
    command: redis-server --appendonly yes
    volumes:
      - data-cache:/data
  search:
    image: solr:6.6.0
    ports:
      - "18983:8983"
    volumes:
      - ./docker/solr/conf/6.x:/myconfig/conf
      - data-search:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - drupal
      - "/myconfig"
  node:
    image: 16nsk/node:1.0.0
    volumes:
      - ./app:/app:delegated
  mail:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "18025:8025"

volumes:
  data-db: {}
  data-cache: {}
  data-search: {}
  web-etc: {}
  composer-cache: {}
  node-modules: {}
